# Generated by Django 4.1.7 on 2023-09-19 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='works_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Note if u delete this all works that done with it will be deleted `(*>﹏<*)′', max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='works',
            name='type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.works_type'),
            preserve_default=False,
        ),
    ]
