# Generated by Django 4.1.7 on 2023-09-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_works_type_works_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='is_prove',
            field=models.BooleanField(),
        ),
    ]
