# Generated by Django 4.1.7 on 2023-09-21 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_causes_studio_studio_manger_works_cause_works_studio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studio_manger',
            name='studio',
        ),
    ]
