# Generated by Django 4.1.7 on 2023-09-21 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_studio_manger_studio'),
    ]

    operations = [
        migrations.AddField(
            model_name='works',
            name='studio_manger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.studio_manger'),
        ),
    ]
