# Generated by Django 4.1.7 on 2023-09-21 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_works_studio_manger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='emploeey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.emploeey'),
        ),
    ]
