# Generated by Django 4.1.7 on 2023-09-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_works_emploeey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='is_prove',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
