# Generated by Django 5.0 on 2023-12-21 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_works_not_ended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='Not_Ended',
            field=models.BooleanField(default=False),
        ),
    ]
